language: rust

rust:
    - nightly-2019-04-07

script:
    - git submodule add --force https://github.com/laohanlinux/parity-common.git
    - cargo build --verbose --all
    - cargo test --verbose --all
